//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesProductos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public int ProductoId { get; set; }
        [Required(ErrorMessage = "El Código del Producto es Obligatorio")]
        public string Producto1 { get; set; }
        [Required(ErrorMessage = "La Descripción es Obligatoria")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El Precio de Venta es Obligatorio")]
        public Nullable<double> Precio { get; set; }
        public Nullable<int> CantExistencia { get; set; }
        public string ImageUrl { get; set; }
    }
}
